// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjwedlUdG1IEtX0wLaTuyOP_FlrWHJdoU',
    appId: '1:627648889924:web:e389bce86db62893aa2811',
    messagingSenderId: '627648889924',
    projectId: 'fir-project-df5be',
    authDomain: 'fir-project-df5be.firebaseapp.com',
    storageBucket: 'fir-project-df5be.appspot.com',
    measurementId: 'G-4VV6CJT619',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxOkPd_Q9CSYOfjTWS01_Zbn--sX_Toms',
    appId: '1:627648889924:android:5f1531f580d220b4aa2811',
    messagingSenderId: '627648889924',
    projectId: 'fir-project-df5be',
    storageBucket: 'fir-project-df5be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3cbEk9D0xPIRpATtAlWkR43MB65SGAmg',
    appId: '1:627648889924:ios:5ee3949eb074369baa2811',
    messagingSenderId: '627648889924',
    projectId: 'fir-project-df5be',
    storageBucket: 'fir-project-df5be.appspot.com',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3cbEk9D0xPIRpATtAlWkR43MB65SGAmg',
    appId: '1:627648889924:ios:5ee3949eb074369baa2811',
    messagingSenderId: '627648889924',
    projectId: 'fir-project-df5be',
    storageBucket: 'fir-project-df5be.appspot.com',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjwedlUdG1IEtX0wLaTuyOP_FlrWHJdoU',
    appId: '1:627648889924:web:0169f5a518af4629aa2811',
    messagingSenderId: '627648889924',
    projectId: 'fir-project-df5be',
    authDomain: 'fir-project-df5be.firebaseapp.com',
    storageBucket: 'fir-project-df5be.appspot.com',
    measurementId: 'G-6F5Z60KELB',
  );
}
